# Generated by Django 4.1.7 on 2023-02-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="office_device_return_time",
            field=models.IntegerField(default=0),
        ),
    ]
