# Generated by Django 4.1.7 on 2023-02-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0002_employee_office_device_return_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee", name="office_device_return_time",
        ),
    ]
